#!/usr/bin/env perl

use strict;
use warnings;
use 5.010;

use Getopt::Long;

my $day;

# TODO: add option all
GetOptions ("day=i" => \$day)
    or die("Error in command line arguments.");

die "Please provide the day number by option '--day'." if ! defined $day;

$day = sprintf("%02d", $day);
die "Provided day must in range from 1 to 25." if $day < 1 or $day > 25;

my $day_solutions = "puzzles/day$day";

for my $part (1..2) {
    my $path_to_part = "$day_solutions/part$part.pm";
    last unless -f $path_to_part;

    system("perl", $path_to_part, "$day_solutions/example.txt");
    system("perl", $path_to_part, "$day_solutions/data.txt");
}
