#!/usr/bin/env perl

use strict;
use warnings;
use 5.010;

use Getopt::Long;

my $day;
GetOptions ("day=i" => \$day)
    or die("Error in command line arguments.");

die "Please provide the day number by option '--day'." if ! defined $day;

$day = sprintf("%02d", $day);
die "Provided day must in range from 1 to 25." if $day < 1 or $day > 25;

for my $part (1..2) {
    system("perl", "puzzles/day$day/part$part.pm", "puzzles/day$day/example.txt");
    system("perl", "puzzles/day$day/part$part.pm", "puzzles/day$day/data.txt");
}
